{
 "title": "sites",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "site_url", "query": { "query": "label_values(site_url)" } }
  ]
 },
 "panels": [
  {
   "title": "Site available",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (site_url) (webmon_site_up)",
     "legendFormat": "{{site_url}}"
    }
   ]
  },
  {
   "title": "Details - $site_url",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "site_url",
   "targets": [
    {}
   ]
  },
  {
   "title": "Certificate expiry",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (site_url) (webmon_certificate_expiry{site_url=~\"^$site_url$\"})"
    }
   ]
  },
  {
   "title": "Site availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "avg by (site_url) (webmon_site_up{site_url=~\"^$site_url$\"})",
     "legendFormat": "UP"
    },
    {
     "expr": "1 - (avg by (site_url) (webmon_site_up{site_url=~\"^$site_url$\"}))",
     "legendFormat": "DOWN"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (name) (webmon_site_latency_seconds{site_url=~\"^$site_url$\"})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}