apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: targets.monitor.clambin.private
spec:
  group: monitor.clambin.private
  scope: Namespaced
  names:
    plural: targets
    singular: target
    kind: Target
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
---
