apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-clusterrole
rules:
  - apiGroups:
      - monitor.clambin.private
    resources:
      - targets
    verbs:
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-clusterrolebind
subjects:
  - kind: ServiceAccount
    name: monitor
    namespace: default
roleRef:
  kind: ClusterRole
  name: monitor-clusterrole
  apiGroup: rbac.authorization.k8s.io
