apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: webmon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webmon-clusterrole
rules:
  - apiGroups:
      - webmon.clambin.private
    resources:
      - targets
    verbs:
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webmon-clusterrolebind
subjects:
  - kind: ServiceAccount
    name: webmon
    namespace: default
roleRef:
  kind: ClusterRole
  name: webmon-clusterrole
  apiGroup: rbac.authorization.k8s.io
