name: Analysis

on:
  push:
  pull_request:

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: checks
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...
          go vet ./...
